export const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE';
export const POST_PROJECT_FAILURE = 'POST_PROJECT_FAILURE';
export const POST_PROJECT_SUCCESS = 'POST_PROJECT_SUCCESS';
export const ADD_PROJECT = 'ADD_PROJECT';
