export const FETCH_PROJECTS_REQUEST = 'FETCH_STUDENTS_REQUEST';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'FETCH_STUDENTS_FAILURE';
export const ADD_PROJECT = 'ADD_PROJECT';